apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.serviceName }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.className }}
  storageClassName: {{ .Values.postgres.storage.className }}
  {{- end }}
