postgres:
  serviceName: postgres
  port: 5432
  containerPort: 5432
  user: myapp_user
  database: myapp_db
  password: mysecretpassword
  storage:
    size: 1Gi
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent

app:
  name: myapp
  replicas: 1
  image:
    repository: ghcr.io/0honeyheart0/my-ci-project/myapp
    tag: latest        
    pullPolicy: IfNotPresent
  servicePort: 80
  jwtSecret: jwt-secret-key
