apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  # Закодируйте ваш секрет: echo -n "your-super-secret-jwt-key" | base64
  jwt-secret-key: eW91ci1zdXBlci1zZWNyZXQtanp0LWtleQ==
