apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-postgres-secret.yaml
  - 02-postgres-storage.yaml
  - 03-postgres-deployment.yaml
  - 04-postgres-service.yaml
  - 05-flask-secret.yaml
  - 06-flask-deployment.yaml
  - 07-flask-service.yaml
