apiVersion: v1
kind: Pod
metadata:
  name: pod-fast
spec:
  containers:
  - name: app
    image: postgres:15-alpine
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-fast
