apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prod
  labels:
    environment: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/prod-data
  storageClassName: manual
