apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  selector:
    matchLabels:
      environment: prod
