name: Deploy to Yandex Managed Kubernetes

on:
  push:
    branches: [ main, app ]

env:
  YC_SA_KEY_JSON: ${{ secrets.YC_SA_KEY_JSON }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Create YC key file
        run: |
          sudo  mkdir -p /home/kali/.config/yandex
          echo '${{ secrets.YC_SA_KEY_JSON }}' > /home/kali/.config/yandex/authorized_key.json
          chmod 600 /home/kali/.config/yandex/authorized_key.json
          cat /home/kali/.config/yandex/authorized_key.json | jq .   # проверка, что JSON валидный

      - name: Debug YC key
        run: |
          ls -la /home/kali/.config/yandex/authorized_key.json
          cat /home/kali/.config/yandex/authorized_key.json | jq . | head -5

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Get kubeconfig
        run: |
          yc config set service-account-key /home/kali/.config/yandex/authorized_key.json
          yc managed-kubernetes cluster get-credentials cat517dhs9533pge7dtn --external
      - name: Deploy with Helm
        run: |
          cd myapp-chart
          helm upgrade --install myapp-release . \
            --namespace myapp --create-namespace \
            --set app.image.repository=ghcr.io/0honeyheart0/my-ci-project/myapp \
            --set app.image.tag=latest \
            --set app.image.pullPolicy=IfNotPresent \
            --set service.type=LoadBalancer

      - name: Debug Helm release
        run: |
          helm list -n myapp
          kubectl get svc -n myapp
          kubectl get pods -n myapp

      - name: Wait for LoadBalancer
        run: |
          kubectl -n myapp wait --for=condition=ready service/myapp-release --timeout=120s
          EXTERNAL_IP=$(kubectl -n myapp get svc myapp-release -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application available at http://$EXTERNAL_IP"
