name: Security Scan

on:
  push:
    branches: [ app, main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Get short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Run Bandit
        run: |
          pip install bandit
          bandit -r . -ll || true
      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - name: Scan Docker image
        run: |
          IMAGE="ghcr.io/0honeyheart0/my-ci-project/myapp:git-${{ steps.sha.outputs.short_sha }}"
          trivy image --severity HIGH,CRITICAL --no-progress $IMAGE
      - name: Scan dependencies
        run: trivy fs --severity HIGH,CRITICAL --no-progress .
