name: Security Scan

on:
  push:
    branches: [ app, main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        run: docker build -t myapp:latest .

      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r . -ll || true

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan local Docker image
        run: trivy image --severity HIGH,CRITICAL --no-progress myapp:latest

      - name: Scan dependencies (filesystem)
        run: trivy fs --severity HIGH,CRITICAL --no-progress .

